### ISSUE TITLE
[96230] Failed to execute script pyi_rth_multiprocessing

### ISSUE THREAD

**Issue by dylancaponi** [ethereum/staking-deposit-cli#159]
Info:

macOS 10.13.6
python 3.7 running in venv

Process:

1. Downloaded latest release files for macOS
2. Ran: `./deposit new-mnemonic --chain mainnet` and `./deposit new-mnemonic`
3. Tried with and without venv
4. Tried installing the requirements from this project and no change.
5. Tried running between installing, updating, and uninstalling new pyinstaller with `pip install pyinstaller`, `pip install -U pyinstaller`, `pip uninstall pyinstaller`

Always the same error:
```
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py", line 18, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "multiprocessing/__init__.py", line 16, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "multiprocessing/context.py", line 6, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "multiprocessing/reduction.py", line 16, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "socket.py", line 52, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "selectors.py", line 12, in <module>
ImportError: dlopen(/var/folders/qm/cs2z9x7d4qxb8903tx5r9b780000gn/T/_MEIflJg8F/select.cpython-37m-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /var/folders/qm/cs2z9x7d4qxb8903tx5r9b780000gn/T/_MEIflJg8F/select.cpython-37m-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/qm/cs2z9x7d4qxb8903tx5r9b780000gn/T/_MEIflJg8F/select.cpython-37m-darwin.so
[96230] Failed to execute script pyi_rth_multiprocessing
```

**Comment by hwwhww** [comment]
Hey @dylancaponi 
The release compressed file only contains the executable binary for running `./deposit new-mnemonic --chain mainnet`. Did you get any error in your step 2?

To compile the binary locally, you can:
1. Download the source code
2. Note: If you want do use pyenv, you have to install Python with `--enable-shared` flag:
    ```
    env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.7
    ```
2. Run `python -m pip install -r ./build_configs/macos/requirements.txt` to install the requirements of building
3. Run `pyinstaller ./build_configs/macos/build.spec` to build the binary. The compiled file will be at `ethereum/eth2.0-deposit-cli/dist/`.

**Comment by dylancaponi** [comment]
Yes, step 2 is where I get this error. This issue is only related to running the downloaded CLI.

Everything runs fine when I build from source with:
```
python3 setup.py install
pip3 install -r requirements.txt
python3 setup.py install
pip3 install -r requirements.txt
```

**Comment by hwwhww** [comment]
It looks like our building server is macOS 10.15, and unfortunately, the built file may not work with the older macOS version (https://github.com/pyinstaller/pyinstaller/issues/3418).

I currently don't have a better answer to resolve it than adding a note that it requires macOS 10.15+.

Thank you for the report!
