### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 42-45: ordinal not in range(256)

### ISSUE THREAD

**Issue by ramast** [ethereum/staking-deposit-cli#302]
I've cloned the repo and installed it using the virualenv method.
When running the app without providing `--language` and/or `--mnemonic_language`, I get an exception.
After adding print statement to debug the error, it originated from the app attempting to print non-unicode characters as shown below.

I've solved the problem by manually passing those parameters.

Debug output:

```
b"Please choose your mnemonic language ['1. \xe7\xae\x80\xe4\xbd\x93\xe4\xb8\xad\xe6\x96\x87', '2. \xe7\xb9\x81\xe9\xab\x94\xe4\xb8\xad\xe6\x96\x87', '3. \xc4\x8de\xc5\xa1
tina', '4. English', '5. Italiano', '6. \xed\x95\x9c\xea\xb5\xad\xec\x96\xb4', '7. Portugu\xc3\xaas', '8. Espa\xc3\xb1ol']:  [english]: "
```

Stack Trace

```
Traceback (most recent call last):
  File "/root/staking-deposit-cli/./staking_deposit/deposit.py", line 61, in <module>
    cli()
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 1964, in full_process_value
    return self.prompt_for_value(ctx)
  File "/root/staking-deposit-cli/staking_deposit/utils/click.py", line 49, in prompt_for_value
    return super().prompt_for_value(ctx)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 1933, in prompt_for_value
    return prompt(
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/termui.py", line 147, in prompt
    value = prompt_func(prompt)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/termui.py", line 128, in prompt_func
    echo(text, nl=False, err=err)
  File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/utils.py", line 273, in echo
    file.write(message)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 42-45: ordinal not in range(256)
```

**Comment by yorickdowne** [comment]
Hey this has been open for a while I see and I’ve just dug into a portion of that code. These aren’t Latin-1, there’s Arabic in there for example. This should render as utf-8 no problem. This sounds like an issue with your environment. Make sure it’s Python 3 not 2, and a recent version of Python 3 at that. “It works here” - you just got to figure out what’s different in your environment.

**Comment by ramast** [comment]
Hi Thanks for taking the time to look into it.

In the traceback you can see lines like this:

    File "/root/staking-deposit-cli/env/lib/python3.9/site-packages/click/core.py", line 1964, in full_process_value
  
Here it clearly shows that not only am I using python3 but a fairly recent version too.

I think either the app drop support for non-latin languages or use utf8 instead of latin1 as you've suggested.

My environment is English but even if it was Arabic, this error shouldn't have happened (I think)

**Comment by yorickdowne** [comment]
Yeah not sure. I build in an English environment, straight Ubuntu, and have not had this issue. The app indeed uses utf-8. Maybe it's an environment configuration thing?

**Comment by ramast** [comment]
Is it possible to use a different language (say Arabic) in `--language` ?  If that works fine we can close this ticket until another person face same problem. If that raises an exception similar to the one I reported, we see how to proceed after.

I don't have the VPS/environment anymore that I tested on otherwise I would tried it

**Comment by chenycallen** [comment]
.\deposit.exe existing-mnemonic --help

***Using the tool on an offline and secure device is highly recommended to keep your mnemonic safe.***

Please choose your language ['1. العربية', '2. ελληνικά', '3. English', '4. Français', '5. Bahasa melayu', '6. Italiano', '7. 日本語', '8. 한국어', '9. Português do Brasil', '10. român', '11. Türkçe', '12. 简体中文']:  [English]: 7
Traceback (most recent call last):
  File "staking_deposit\deposit.py", line 63, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1257, in invoke
  File "click\core.py", line 700, in make_context
  File "click\core.py", line 1048, in parse_args
  File "click\core.py", line 1630, in handle_parse_result
  File "click\core.py", line 123, in invoke_param_callback
  File "click\core.py", line 950, in show_help
  File "click\core.py", line 570, in get_help
  File "click\core.py", line 975, in get_help
  File "click\core.py", line 1003, in format_help
  File "click\core.py", line 1024, in format_options
  File "staking_deposit\utils\click.py", line 56, in get_help_record
  File "staking_deposit\utils\click.py", line 19, in _value_of
  File "staking_deposit\cli\existing_mnemonic.py", line 34, in <lambda>
  File "staking_deposit\utils\intl.py", line 68, in load_text
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe6 in position 64: illegal multibyte sequence
[49636] Failed to execute script 'deposit' due to unhandled exception!
