### ISSUE TITLE
"The given withdrawal credentials is matching the old BLS withdrawal credentials that mnemonic generated."

### ISSUE THREAD

**Issue by Mariospartner** [ethereum/staking-deposit-cli#335]
Hello,

I have a bunch of validators all with 0x00 credentials. They were not deposited at the same time.

When I first tried running "ethdo" to convert to bls, I only get output of around 33% of the actual amount of validators. It gives the error message; "Failed to find validator using the provided mnemonic, validator=xxx, pubkey=x0213457".

I am 100% sure its the correct mnemonic thats been used for all my deposits. I run all validators on the same staking machine. All visible in the "validators" folder (including the above error pubkey). When I shut down the machine all validators miss attestations.

I thought I would try staking-deposit-cli hoping that would fix the problem. But here the error message is the following;
"The given withdrawal credentials is matching the old BLS withdrawal credentials that mnemonic generated."

Does anyone knows what this means? How can I solve this?

```
**[Warning] you are setting an Eth1 address as your withdrawal address. Please ensure that you have control over this address.**

Traceback (most recent call last):
  File "staking_deposit\deposit.py", line 63, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "staking_deposit\cli\generate_bls_to_execution_change.py", line 182, in generate_bls_to_execution_change
  File "staking_deposit\utils\validation.py", line 257, in validate_bls_withdrawal_credentials_matching
staking_deposit.exceptions.ValidationError:
The given withdrawal credentials is matching the old BLS withdrawal credentials that mnemonic generated.

[49408] Failed to execute script 'deposit' due to unhandled exception!
```

**Comment by Mariospartner** [comment]
If I understood this correctly "The given withdrawal credentials is matching the old BLS withdrawal credentials that mnemonic generated."
There should be some new BLS withdrawal credentials that I am not aware of. Where is that?
