### ISSUE TITLE
generate-bls-to-execution-change fails

### ISSUE THREAD

**Issue by jerryji** [ethereum/staking-deposit-cli#342]
staking_deposit-cli-d83c312 fails to generate-bls-to-execution-change --

```
staking_deposit-cli-d83c312-linux-amd64$ ./deposit --language=english generate-bls-to-execution-change --chain=mainnet 

***Using the tool on an offline and secure device is highly recommended to keep your mnemonic safe.***

Please enter your mnemonic separated by spaces (" "). Note: you only need to enter the first 4 letters of each word if you'd prefer.: sister protect peanut hill ready work profit fit wish want small inflict flip member tail between sick setup bright duck morning sell paper worry
Please enter the index position for the keys to start generating withdrawal credentials in ERC-2334 format. [0]: 
Please enter a list of the validator index number(s) of your validator(s) as identified on the beacon chain. Split multiple items with whitespaces or commas.: 2599
Please enter a list of the old BLS withdrawal credentials of your validator(s). Split multiple items with whitespaces or commas.: 0x0031ab83e9e6f6b7cc7381e7138d42d3f1f14a0e60293663104b68c53e121402
Please enter the 20-byte execution address for the new withdrawal credentials. Note that you CANNOT change it once you have set it on chain.: 0x3434343434343434343434343434343434343434

**[Warning] you are setting an Eth1 address as your withdrawal address. Please ensure that you have control over this address.**

Repeat your execution address for confirmation.: 0x3434343434343434343434343434343434343434

**[Warning] you are setting an Eth1 address as your withdrawal address. Please ensure that you have control over this address.**

Traceback (most recent call last):
  File "staking_deposit/deposit.py", line 63, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "staking_deposit/cli/generate_bls_to_execution_change.py", line 182, in generate_bls_to_execution_change
  File "staking_deposit/utils/validation.py", line 257, in validate_bls_withdrawal_credentials_matching
staking_deposit.exceptions.ValidationError: 
The given withdrawal credentials is matching the old BLS withdrawal credentials that mnemonic generated.

[7329] Failed to execute script 'deposit' due to unhandled exception!
```

**Comment by jerryji** [comment]
In https://github.com/ethereum/staking-deposit-cli/pull/313 , the example bls_withdrawal_credential used for validator_indice=1 is "0x00bd0b5a34de5fb17df08410b5e615dda87caf4fb72d0aac91ce5e52fc6aa8de" (how is it obtained?), but validator_index=1's actual withdrawal credential on mainnet should be "0x0092c20062cee70389f1cb4fa566a2be5e2319ff43965db26dbaa3ce90b9df99", which when used, will result in the same "The given withdrawal credentials is matching the old BLS withdrawal credentials..." error.
